[build]
  command = "ng build --configuration=production"
  publish = "dist/tecnicayservicios/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  # Si alguna vez tenés problemas de peer deps, podés descomentar:
  # NPM_FLAGS = "--legacy-peer-deps"
  # Y si llegara a tirar errores de memoria en build Angular:
  # NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
